### PR TITLE
Upgrade owasp plugin and fix vulnerabilities

### PR DESCRIPTION
**Pull request by vahidiazar**

### CODE REVIEW

**Comment by vahidiazar** [comment]
closes #57

**Comment by marcelstoer** [comment]
@RobWin can you cut another release with this fix included?

**Comment by vahidiazar** [comment]
Hi @RobWin, any chance to release with these changes?

**Comment by RobWin** [comment]
Difficult. The whole release process is outdated :( 
I don't have time to maintain it anymore. Anyone interested? I can transfer it?

**Comment by RobWin** [comment]
At least deploying the SNAPSHOT version still works. 
https://oss.jfrog.org/artifactory/webapp/#/builds/assertj-swagger/1610352467594/1610352467547/published%20/io.github.robwin:assertj-swagger:0.9.0-SNAPSHOT

**Comment by RobWin** [comment]
Publishing to Bintray works.
But sync to Maven Central fails

**Pull request merged**
